### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Huii** [ChangWeiTan/MultiRocket#6]
Hello again,

I'm attempting to run MultiRocket with MINIROCKET kernels on extracted features of my signals. I know that this doesn't make much sense but I still want to include the results in my comparison to SHOW that it doesn't make much sense. ;-)

However, I run into the following issue:

```
Traceback (most recent call last):
  File "PathTo\MultiRocket.py", line 47, in performMultiRocketForMuscleData
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 77, in fit
    x_train_transform = minirocket.transform(x_train, self.kernels)
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  [...]
  File "PathTo\MultiRocket.py", line 50, in performMultiRocketForMuscleData
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 77, in fit
    x_train_transform = minirocket.transform(x_train, self.kernels)
ZeroDivisionError: division by zero
```

My data looks as follows:

```
[[[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ... -4.09381799e-02
    4.16528992e+02  1.73496406e+05]]

 [[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ... -1.91501305e-02
    4.16400543e+02  1.73389422e+05]]

 [[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ... -2.44050100e-02
    4.17635895e+02  1.74419734e+05]]

 ...

 [[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ...  1.30052060e-01
    3.21637360e+02  1.03450602e+05]]

 [[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ...  1.24421462e-01
    3.20599060e+02  1.02783758e+05]]

 [[ 4.88281250e-04  9.76562500e-04  1.46484375e-03 ...  1.21354438e-01
    3.20987671e+02  1.03033086e+05]]]
```

It seems like somewhere a quick test for sane inputs is missing. Thank you very much for any help.

// edit:

The same problem also exists for the ROCKET part by the way:

```
  File "PathTo\MultiRocket.py", line 44, in performMultiRocketForMuscleData
    yhat_train = classifier.fit(x_trainScaled, y_train, predict_on_train=False)
  File "PathTo\MultiRocket\multirocket\multirocket.py", line 88, in fit
    x_train_transform = rocket.apply_kernels(x_train, self.kernels, self.feature_id)
ZeroDivisionError: division by zero
```

**Comment by ChangWeiTan** [comment]
Hi @Huii , I am not sure if this makes sense. First, do your features have a special order in time/space? If not, then it does not make sense to apply convolutions on such features because the order of the features makes a difference.  Then, how many features do you have (i.e. how many columns). Rocket works off a minimum length of 7 while minirocket needs 9. It seems like this division by 0 is due to some features. Could you try running it with feature_id=23 (PPV) or feature_id=49 (PPV+Max)? Actually in such cases, it is better to email me a simple working example so that I can help debug better. 

Yes the quick tests are missing as this is still a raw source code for our paper. I will add on more tests in the future once our paper is accepted.

**Comment by Huii** [comment]
Thank you very much again! Changing the "feature_id" parameter to 49 did the trick for me. I have a feature vector of length > 30, which should be fine.
