### ISSUE TITLE
what does itr represent?

### ISSUE THREAD

**Issue by turmeric-blend** [ChangWeiTan/MultiRocket#7]
Hi this is really nice work you've done :)

I have a simple question for [this line of code](https://github.com/ChangWeiTan/MultiRocket/blob/efff79a6bfd5f49608646ea4ba442cedf43c4385/main_ucr.py#L120). In what situation will this `if` statement be run? What does `itr > 0` represent here? I know you mentioned `-i --iteration: determines the resample of the UCR datasets`, but its still not immediately clear to me what `itr` means. Sorry for this basic question, thanks for your help :)

**Comment by ChangWeiTan** [comment]
Hi @turmeric-blend, the itr in this code here means the resampling of the data. As you might know, for the UCR datasets, there is a default train test split, that's itr=0 (or resample 0), which everyone has been using since the introduction of the archive. We followed the benchmarking guidelines from the UEA group where the UCR datasets are shuffled (mixing the train and test) and resampled for 30 times. Thus, each iteration here refers to the runs and we load the train and test indices for each run to ensure that each algorithm is trained on the same set and they are comparable.  Finally, the average accuracy was used to compare the algorithms.

**Comment by turmeric-blend** [comment]
oh I see, didn't know this as im new to the UCR dataset. Thanks !
